---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cluster-issuer
spec:
  acme:
    server: 'https://acme-v02.api.letsencrypt.org/directory'
    privateKeySecretRef:
      name: acme-account-private-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              key: api-token
              name: cloudflare-api-token-secret

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apps-okd-ankersen-dev-certificate
  namespace: openshift-ingress
spec:
  commonName: apps.okd.ankersen.dev
  dnsNames:
    - "apps.okd.ankersen.dev" 
    - "*.apps.okd.ankersen.dev"
    - "*.ankersen.dev"
  secretName: apps-okd-ankersen-dev-tls
  isCA: false
  privateKey:
    algorithm: ECDSA
    rotationPolicy: Always
    size: 384
  issuerRef:
    group: cert-manager.io
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-okd-ankersen-dev-certificate
  namespace: openshift-config
spec:
  commonName: api.okd.ankersen.dev
  dnsNames:
    - "api.okd.ankersen.dev"
    - "*.ankersen.dev"
  secretName: api-okd-ankersen-dev-tls
  isCA: false
  privateKey:
    algorithm: ECDSA
    rotationPolicy: Always
    size: 384
  issuerRef:
    group: cert-manager.io
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer    