---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: br-ex-vlan10
spec:
  desiredState:
    ovn:
      bridge-mappings:
        - bridge: br-ex
          localnet: br-ex-vlan10
          state: present