apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: nncp-porter
spec:
  nodeSelector:
    kubernetes.io/hostname: porter
  desiredState:
    interfaces:
      - name: enp8s0f3u1
        type: ethernet
        state: up
        ipv4:
          enabled: false
      - name: enp8s0f3u1.20
        type: vlan 
        state: absent
        vlan:
          base-iface: enp8s0f3u1 
          id: 20  
      - name: br-vm
        type: linux-bridge
        bridge:
          options:
            stp: 
              enabled: true
          port:
            - name: enp8s0f3u1
        state: up
      - name: br0
        type: ovs-bridge
        state: absent
        bridge:
          options:
            stp: 
              enabled: true
          port:
            - name: enp8s0f3u1
    ovn:
      bridge-mappings:
      - localnet: br0-network
        bridge: br0 
        state: absent  
