---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: nfs.csi.k8s.io   
parameters:
  server: brixton.ankersen.dev
  share:  /volume1/okd
  subDir: ${pvc.metadata.namespace}-${pvc.metadata.name}-${pv.metadata.name}
mountOptions:
  - nfsvers=4
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: True

---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
deletionPolicy: Delete
driver: nfs.csi.k8s.io
metadata:
  name: nfs-csi
