---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: minecraft-seamus
  labels:
    app: minecraft-seamus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-seamus
  template:
    metadata:
      namespace: minecraft
      labels:
        app: minecraft-seamus
    spec:
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: minecraft-seamus-pvc
      containers:
        - name: minecraft-seamus
          image: >-
            itzg/minecraft-server@sha256:818b1b2ffbc78dfa6c27115b1a0ccace4779de4df8d34d87006a60831e2ed13b
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
              - ALL
          ports:
            - containerPort: 25575
              protocol: TCP
            - containerPort: 25565
              protocol: TCP
          env:
            - name: 'EULA'
              value: 'TRUE'
            - name: 'TZ'
              value: 'America/Chicago'
            - name: 'OPS'
              value: 'EmeraldDen,TubOfGoo'
            - name: 'MAX_MEMORY'
              value: '6G'
            - name: 'TYPE'
              value: 'CURSEFORGE'
            - name: 'CF_SERVER_MOD'
              value: 'Better-MC-FORGE-Server-Pack-1.19.2.zip'
          resources:
            limits:
              cpu: '1'
              memory: 8Gi
            requests:
              cpu: '1'  
          volumeMounts:
            - name: data-volume
              mountPath: /data
          readinessProbe:
            exec:
              command:
                - mc-monitor
                - status
                - '--host'
                - localhost
                - '--port'
                - '25565'
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
  revisionHistoryLimit: 2
  strategy:
    type: Recreate

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: minecraft
  name: minecraft-seamus-pvc
  labels:
    app: minecraft-seamus
spec:
  selector:
    matchLabels:
      app: minecraft-seamus
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  volumeMode: Filesystem
  storageClassName: nfs-wait

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-seamus-pv
  labels:
    app: minecraft-seamus
spec:
  capacity:
    storage: 500Mi 
  accessModes:
  - ReadWriteOnce
  nfs: 
    path: /volume1/ocp-minecraft-seamus
    server: brixton.ankersen.dev
  storageClassName: nfs-wait

---
kind: Service
apiVersion: v1
metadata:
  namespace: minecraft
  name: minecraft-seamus
  labels:
    app: minecraft-seamus
spec:
  ports:
    - name: port-rcon
      protocol: TCP
      port: 25575
      targetPort: 25575
      nodePort: 30175
    - name: port-game
      protocol: TCP
      port: 25565
      targetPort: 25565
      nodePort: 30165
  type: NodePort
  selector:
    app: minecraft-seamus
